#### 1. Load CSV dataset into pandas dataframe

In [168]:
# import libraries
import pandas as pd

In [169]:
# read the dataset
df = pd.read_csv("combined_dataset.csv")
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

#### 2. Explore data

In [170]:
# display the first few rows of the dataset
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [171]:
# display the last few rows of the dataset
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [172]:
# display the shape of the dataset
df.shape

(1000, 24)

In [173]:
# display the column names of the dataset
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [174]:
# display the data types of the columns in the dataset
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

#### 3. Handling missing values 
- Fill the missing values with either zeros, mean, median or category wise.
- Or we can drop the rows with missing values

In [175]:
# identify missing values in the dataset
df.isnull()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,True,True,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,True,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,True,True,False,False,False,False

In [176]:
# count of null values by columns
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [177]:
# fill the missing values according to the category of the column
df = df.fillna({
    'discount': 0,
    'videos': 'No Video',
    'what_customers_said': 'No Reviews',
    'variations': 'No Variations',
    'seller_name': 'Unknown Seller',
    'seller_information': 'Not Available',
})
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Reviews,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]",No Video,Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Reviews,Tru███m R███il,"[{""size"":""Onesize""}]",No Video,Sho███o. ███-10█████████enu███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",No Reviews,Unknown Seller,"[{""size"":""Medium""}]",No Video,Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

#### 4. Perform basic operations
- Filtering 
- Selecting columns

In [178]:
# filter rows where rating >= 4.0 and ratings_count >=500
df.loc[(df["rating"] >= 4.0) & (df["ratings_count"] >= 500)]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
24,15115018,Jockey,Non-Wired Non-Padded Combed Cotton Workout Bra...,4.4,1582,579,0.0,"""₹579.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":90,""2_stars"":25,""3_stars"":93,""4_star...",No Reviews,Tru███m R███il,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""Ov...",No Video,Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bra
117,18962952,Athena,Lavender Solid Accordion Pleats Wrap Dress,4.2,3797,2799,60.0,"""₹1,119.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":312,""2_stars"":170,""3_stars"":272,""4_s...","[{""percentage"":""72"",""value_name"":""Fit, Just Ri...",Ape███ppa███s -██████,"[{""size"":""XS"",""value"":""23.0in"",""value_name"":""S...",No Video,"Plo███o. ███, P█████████2 S███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
143,10691426,SASSAFRAS,Black & Beige Ikat Print Cotton Shirt Dress,4.5,4441,2199,65.0,"""₹769.00""",INR,http://assets.myntassets.com/assets/images/106...,...,"{""1_star"":126,""2_stars"":78,""3_stars"":288,""4_st...","[{""percentage"":""79"",""value_name"":""Fit, Just Ri...",ARD███ Re███l C███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",No Video,Khe███ No███76/█████████il ███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
166,13558254,Tokyo Talkies,Women Peach-Coloured Printed Fit and Flare Dress,4.1,934,1349,59.0,"""₹1,349.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":59,""2_stars"":38,""3_stars"":114,""4_sta...","[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Bu...",No Video,Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",dresses
173,13391540,Mast & Harbour,EcoVero Women Yellow & White Abstract Printed ...,4.1,576,1999,66.0,"""₹679.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":47,""2_stars"":24,""3_stars"":49,""4_star...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",SWARR,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",No Video,D-2███Sec███ 06█████████uta███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
176,13382036,plusS,Women Olive Green Accordion Pleated Midi A-Lin...,4.2,623,1899,83.0,"""₹322.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":47,""2_stars"":31,""3_stars"":60,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",Shi███Int███ati█████████rel███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",No Video,Fir███and███con█████████A 3███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",dresses
209,10564232,PRITA BY PRIYAASI,Multicoloured Gold-Plated Beaded Handcrafted C...,4.3,727,1130,69.0,"""₹350.00""",INR,http://assets.myntassets.com/assets/images/105...,...,"{""1_star"":48,""2_stars"":26,""3_stars"":62,""4_star...",No Reviews,PRI███DES███S P█████████MIT███,"[{""size"":""Onesize""}]","[""rw-10564232_cae700""]",PRI███DES███S P█████████MIT███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
212,10125225,KARATCART,Peach-Coloured & Off-White Gold-Plated Stone-S...,4.1,872,1568,73.0,"""₹423.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":92,""2_stars"":45,""3_stars"":70,""4_star...",No Reviews,KOK███V G███AL █████████,"[{""size"":""Onesize""}]",No Video,Sho███58-███Sec█████████ain███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",earrings
258,15787112,Mamaearth,Oil-Free Face Moisturizer With Turmeric & Saff...,4.3,903,319,12.0,"""₹280.00""",INR,http://assets.myntassets.com/assets/images/157...,...,"{""1_star"":40,""2_stars"":23,""3_stars"":77,""4_star...",No Reviews,Hon███ Co███mer█████████Lim██████,"[{""size"":""75-100 ML""}]",No Video,Plo███o 6███4th█████████LM ███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",face-moisturisers
448,12524816,HERE&NOW,Women Blue & Golden Ethnic Printed Straight Kurta,4.1,937,1199,0.0,"""₹1,199.00""",INR,http://assets.myntassets.com/assets/images/125...,...,"{""1_star"":55,""2_stars"":50,""3_stars"":127,""4_sta...","[{""percentage"":""80"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""44.0in"",""value_name"":""Fr...",No Video,Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",kurtas
473,13446422,Biba,Women Cream-Coloured Motifs Print Panelled Cot...,4.4,749,4995,50.0,"""₹2,997.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":44,""2_stars"":17,""3_stars"":56,""4_star...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",Fla███tar███mme██████,"[{""size"":""S"",""value"":""33.0in"",""value_name"":""To...","[""rw-13446422_cae700""]","1st███oor███abi█████████02,███████████████████...",No Variations,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",kurta-sets
508,16254760,Zaveri Pearls,Set Of 3 Gold-Plated White & Green Kundan-Stud...,4.2,504,2250,81.0,"""₹2,250.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":33,""2_stars"":26,""3_stars"":57,""4_star...",No Reviews,Unknown Seller,"[{""size"":""Onesize"",""value"":""2.5in"",""value_name...","[""rw-16254760_cae700"",""https://videos.myntasse...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",ring
582,17280264,HIGHLANDER,Men Sea Green & Pink Slim Fit Printed Cotton C...,4.2,1246,1199,59.0,"""₹491.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":87,""2_stars"":35,""3_stars"":118,""4_sta...","[{""percentage"":""74"",""value_name"":""Fit, Just Ri...",Fla███tar███mme██████,"[{""size"":""39"",""value"":""41.0in"",""value_name"":""C...",No Video,"1st███oor███abi█████████02,███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
603,17293106,DressBerry,Women Pink & White Slim Fit Floral Printed Cas...,4.2,622,1599,59.0,"""₹591.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":50,""2_stars"":26,""3_stars"":40,""4_star...",No Reviews,Pat███a H███e,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",No Video,B/4███ Ra███ Ra█████████le ███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
773,6510138,Roadster,Men Black Solid Hooded Sweatshirt,4.3,959,1999,50.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/651...,...,"{""1_star"":49,""2_stars"":29,""3_stars"":68,""4_star...","[{""percentage"":""84"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""40.5in"",""value_name"":""Ch...","[""rw-6510138_cae700""]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",sweatshirts
922,17760062,H&M,Women Brown Solid Low Waist Flared Twill Trousers,4.2,608,1499,25.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/177...,...,"{""1_star"":53,""2_stars"":30,""3_stars"":38,""4_star...","[{""percentage"":""70"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""23"",""value"":""23.0in"",""value_name"":""T...",No Video,Not Available,"[{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",trousers
941,8426447,WROGN,Men Navy Blue Striped Henley Neck T-shirt,4.2,514,1599,50.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/842...,...,"{""1_star"":36,""2_stars"":16,""3_stars"":46,""4_star...",No Reviews,Unknown Seller,"[{""size"":""S"",""value"":""37.25in"",""value_name"":""C...","[""rw-8426447_cae700""]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
944,9213113,Roadster,The Lifestyle Co Men White Printed Round Neck...,4.1,994,799,50.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/921...,...,"{""1_star"":74,""2_stars"":41,""3_stars"":108,""4_sta...","[{""percentage"":""68"",""value_name"":""Fit, Just Ri...",Unknown Seller,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-9213113_cae700""]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
974,16293014,Nayo,Navy Blue & Maroon Printed Tunic,4.2,514,1199,43.0,"""₹683.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":31,""2_stars"":24,""3_stars"":54,""4_star...",No Reviews,Bhu███E R███il █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",No Video,"F-███-A,███t, █████████flo███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tunics
975,16293018,Nayo,Black & White Printed Cotton Kurti,4.3,687,1199,43.0,"""₹683.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":32,""2_stars"":28,""3_stars"":51,""4_star...",No Reviews,Bhu███E R███il █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",No Video,"F-███-A,███t, █████████flo███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tunics
988,8076639,French Connection,Women Charcoal Grey Analogue Watch FC1317RGM,4.4,563,6250,60.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/807...,...,"{""1_star"":35,""2_stars"":21,""3_stars"":22,""4_star...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8076639_cae700"",""https://videos.myntasset...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.0,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",No Reviews,DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

In [179]:
# select columns "product_id", "title", "product_description", and "final_price"
df[["product_id", "title", "product_description", "final_price"]]

,product_id,title,product_description,final_price
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,"""₹3,995.00"""
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,"""₹2,899.00"""
2,17633752,Lavie,Aries Women Pink Mini Backpack,"""₹2,999.00"""
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,"""₹1,675.00"""
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,"""₹2,899.00"""
...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,"""₹11,890.00"""
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,"""₹8,900.00"""
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,"""₹7,950.00"""
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,"""₹2,636.00"""
999,18601682,BOLDFIT,Purple Textured Yoga Mat,"""₹699.00"""

#### 5. Remove duplicates

In [180]:
# check for duplicate rows in the dataset
df.duplicated().sum()

np.int64(0)

In [181]:
# drop duplicate rows from the dataset
df.drop_duplicates()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Reviews,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""pi-13698258""]",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Reviews,Unknown Seller,"[{""size"":""Onesize""}]",No Video,Not Available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Reviews,Tru███m R███il,"[{""size"":""Onesize""}]",No Video,Sho███o. ███-10█████████enu███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",No Reviews,Unknown Seller,"[{""size"":""Medium""}]",No Video,Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

####  6 .Create a derived column (total_amount = price * quantity)
- "quantity" column is not given in the dataset so we derieve it through "rating_count" column.
- We use rating_count because it gives the approximate value of how many people bought the item.
- But we have derieved new "quantity" column as it should not contain any zeros, as total price will become zero.
- Then we derieved "total_price" column and do some formatting on that.

In [182]:
df['quantity'] = df['ratings_count'].clip(lower=1) # to avoid zero quantity
df['total_price'] = (df['quantity'] * df['initial_price'])   # calculate total price
df['total_price'] = df['total_price'].apply(lambda x: f'₹{x:,.0f}') # format total price with currency symbol and commas
df.head(20)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_price
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,15,"₹59,925"
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,67,"₹194,233"
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,Unknown Seller,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,226,"₹677,774"
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,Unknown Seller,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Not Available,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1052,"₹1,762,100"
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,Unknown Seller,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video,Not Available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,12,"₹34,788"
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,0.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",No Video,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories,42,"₹58,758"
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,Unknown Seller,"[{""size"":""Onesize""}]",No Video,Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels,5,"₹6,995"
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,Unknown Seller,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",No Video,Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,10,"₹29,990"
8,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,Unknown Seller,"[{""size"":""Super King""}]",No Video,Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,22,"₹65,978"
9,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,Unknown Seller,"[{""size"":""Double King""}]",No Video,Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,7,"₹15,393"
10,8430275,MYTRIDENT,Sea Green Floral Flat 120 TC Cotton 1 Queen Be...,4.4,26,2199,46.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,Unknown Seller,"[{""size"":""Double Queen""}]",No Video,Not Available,"[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,26,"₹57,174"
11,18346118,Arrabi,Pink & White Graphic 300 TC King Bedsheet with...,0.0,0,3329,74.0,"""₹865.00""",INR,http://assets.myntassets.com/assets/images/183...,...,Sig███Ove███as,"[{""size"":""Super King""}]",No Video,Old███. 2███162█████████o. ███████████████████...,"[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets,1,"₹3,329"
12,18327434,BELLA CASA,Unisex Blue Bedsheets,0.0,0,1499,73.0,"""₹404.00""",INR,http://assets.myntassets.com/assets/images/183...,...,Bel███Cas███ash█████████ail█████████,"[{""size"":""Single""}]",No Video,E-1███103███PIP█████████ IN███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",bedsheets,1,"₹1,499"
13,18492504,ROMEE,Blue & Beige Conversational 160 TC King Bedshe...,3.9,10,3499,65.0,"""₹3,499.00""",INR,http://assets.myntassets.com/assets/images/184...,...,Unknown Seller,"[{""size"":""Double King""}]",No Video,Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,10,"₹34,990"
14,13729978,DDecor,White & Brown Floral 350 TC Cotton 1 King Beds...,3.6,15,1599,20.0,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/137...,...,Unknown Seller,"[{""size"":""Double King""}]",No Video,Not Available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,15,"₹23,985"
15,19788630,Home Ecstasy,140tc Pure Cotton printed Teal Blue Single Bed...,4.5,6,1199,42.0,"""₹1,199.00""",INR,http://assets.myntassets.com/assets/images/197...,...,Unknown Seller,"[{""size"":""Single""},{""size"":""Double Queen""}]",No Video,Not Available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,6,"₹7,194"
16,20296382,DREAM WEAVERZ,Grey & Coral Printed 220 TC Glazed Cotton King...,3.8,18,2599,78.0,"""₹2,599.00""",INR,http://assets.myntassets.com/assets/images/202...,...,Unknown Seller,"[{""size"":""Double Queen""}]",No Video,Not Available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,18,"₹46,782"
17,18346134,Arrabi,Pink & Grey Striped 300 TC King Cotton Bedshee...,4.3,12,6329,76.0,"""₹6,329.00""",INR,http://assets.myntassets.com/assets/images/183...,...,Unknown Seller,"[{""size"":""Super King""}]",No Video,Not Available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets,12,"₹75,948"
18,22409156,Kastner,Women Textured Tang Slim Belt,3.8,9,1399,84.0,"""₹223.00""",INR,http://assets.myntassets.com/assets/images/224...,...,Kas███r L███her█████████Pvt██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",No Video,A-5███ADA███R V█████████ De█████████████████████,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",belts,9,"₹12,591"
19,18985918,Tommy Hilfiger,Women Navy Blue Embroidered High-Neck Pure Cot...,4.1,11,2999,40.0,"""₹1,799.00""",INR,http://assets.myntassets.com/assets/images/189...,...,PVH███VIN███ASH█████████TE ███████████████,"[{""size"":""XXS"",""value"":""21.8in"",""value_name"":""...",No Video,PVH███vin███ash█████████tdN███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bodysuit,11,"₹32,989"

#### 7. Save the cleaned dataset

In [183]:
df.to_csv("Cleaned_dataset.csv", index=False)